### ISSUE TITLE
Implement font enumerating and other functions

### ISSUE THREAD

**Issue by aochagavia** [Connicpu/directwrite-rs#1]
I would like to use this crate in Servo for font rendering on Windows (currently the MSVC build cannot display text). It is clear that I will need some functions that are not yet implemented in this crate. Would it be ok to submit PRs in order to add them?

**Comment by aochagavia** [comment]
Alternatively, I could create a new crate that depends on this one.

**Comment by Connorcpu** [comment]
Hey sorry this crate has been inactive for a while, I wasn't checking my github notifications due to being busy with school. I'd be happy to merge a PR for that feature, or I could do it myself given a bit of time!

**Comment by aochagavia** [comment]
No problem! The Servo folks ended up implementing minimal support for windows fonts, but that is pretty basic at the moment. See https://github.com/servo/servo/pull/13567 for the implementation details, in case you are interested.

I don't have the time/motivation to work on this crate right now and I am not involved in Servo development, so I have no urgent need for any of these features. Thanks anyway for your message.

**Comment by Connicpu** [comment]
Looks like we've got all of this in now thanks to #5!
